### ISSUE TITLE
Po zmene od markizy prestal fungovat add-on

### ISSUE THREAD

**Issue by Bigwolf47** [kodi-czsk/plugin.video.markiza.sk#61]
Ahojte
V utorok, 7.2.2023 prestal fungovat add-on markizy.
Predpokladam ze je to spojene s touto zmenou ktoru markiza v ten den urobila:
https://zive.aktuality.sk/clanok/ZxnjGgw/markiza-stazi-pristup-k-bezplatnemu-televiznemu-archivu/

Najprv som myslel ze bude stacit pouzit nove konto kedze stare sa pri tejto zmene zmazalo, lenze nefunguje to ani s druhym kontom cez ktore sa na markizu cez web portal viem prihlasit.

Moj odhad je ze zmena nastala niekde v prihlasovani sa kedze url minimalne na zive vysielanie je stale rovnake. Taktiez v logu to hadze chybu v mieste prihlasovania. Vyzera to ze to nenaslo token na prihlasenie, ale to uz je mimo moju parketu.

Pouzivam Kodi 18.9. Leia
Verzia pluginu 1.4.2

Error log:
```
2023-02-10 20:06:48.328 T:1585431424  NOTICE: ["Initializing provider markiza.sk with settings {'lang': '0', 'downloads': '', 'quality': '1'}"]
2023-02-10 20:06:49.001 T:1585431424   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.markiza.sk/default.py", line 44, in <module>
                                                XBMCMarkizaContentProvider(provider,settings,__addon__).run(params)
                                              File "/storage/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 87, in run
                                                return self.play({'url': params['play'], 'info': params})
                                              File "/storage/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 186, in play
                                                stream = self.resolve(item['url'])
                                              File "/storage/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 353, in resolve
                                                return self.provider.resolve(item, select_cb=select_cb)
                                              File "/storage/.kodi/addons/plugin.video.markiza.sk/resources/lib/markiza.py", line 199, in resolve
                                                result = self._resolve_live(item, relogin=True)
                                              File "/storage/.kodi/addons/plugin.video.markiza.sk/resources/lib/markiza.py", line 254, in _resolve_live
                                                token = re.search(r'name=\"_token_\" value=\"(\S+?)\">',httpdata).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
2023-02-10 20:06:49.210 T:1936742848   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.markiza.sk/?play=68747470733a2f2f766964656f6172636869762e6d61726b697a612e736b2f6c6976652f312d6d61726b697a61&cp=6d61726b697a612e736b&]
```

Dakujem za tento super addon ktory pouzivam uz 2 roky, dufam ze budem aj nadalej.

Pokial je to len problem na mojej strane tak nevahajte mi dat vediet ale podla prvej analyzy nevidim nic co by mohlo tomu nasvedcovat.

**Comment by jose1711** [comment]
Medzicasom opravene, ku dnesku funguje Live prehravanie i archiv bez problemov (v 1.5.6)
